spring:
  web:
    resources:
      static-locations: classpath:/static/
  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: true
  application:
    name: donut
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/donut
    username: donut
    password: donut
  data:
    mongodb:
      uri: mongodb+srv://gogumat1212:sbfjs5@cluster0.bops8.mongodb.net/vectorDB
  ai:
    vectorstore:
      mongodb:
        collection-name: document
        initialize-schema: false
        path-name: content-embedding
        indexName: vector_index
    openai:
#      api 키 환경설정 필요
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
      image:
        options:
          model: "dall-e-3"
# 마이바티스 설정
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

hybrid-search:
  tmm:
#    BM 25 점수가 이론상 무한대  5 이상이면 만점취급
    text-score:
      max-value: 5
      min-value: 0
      # 만약에 25점 나왔으면 만점 5점도 만점

      # -1 ~ 1    0 ~ 5
      # 0 ~ 1
      #
  weight:
    # 정규화 된 0 ~ 1 점수

    # 시도하면서 찾은 잘 나온 값으로 설정
    # 키워드에 중점 vs 의미 중점
    vector-score: 0.5
    text-score: 0.5