spring:
  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: true
  application:
    name: donut
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/donut
    username: donut
    password: donut
  data:
    mongodb:
      uri: mongodb+srv://gogumat1212:sbfjs5@cluster0.bops8.mongodb.net/vectorDB
  ai:
    vectorstore:
      mongodb:
        collection-name: document
        initialize-schema: false
        path-name: content-embedding
        indexName: vector_index
    openai:
#      api 키 환경설정 필요
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
# 마이바티스 설정
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

hybrid-search:
  tmm:
    text-score:
      max-value: 5
      min-value: 0
  weight:
    vector-score: 0.5
    text-score: 0.5

logging:
  level:
    root: INFO  # 루트 로거의 레벨을 INFO로 설정
  file:
    name: application.log  # 파일로 로깅할 경우, 로그 파일의 이름 설정
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 콘솔 로그 형식