spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: skm5860@gmail.com  # 여기에 이메일 주소
    password: mtkrbrjqlunwqfzf   # 이메일 애플리케이션 비밀번호 설정 필요 (Google 설정에서 확인 가능)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  web:
    resources:
      static-locations: classpath:/static/
  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: true
  application:
    name: donut
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/donut
    username: donut
    password: donut
  data:
    mongodb:
      uri: mongodb+srv://gogumat1212:sbfjs5@cluster0.bops8.mongodb.net/vectorDB
  ai:
    vectorstore:
      mongodb:
        collection-name: document
        initialize-schema: false
        path-name: content-embedding
        indexName: vector_index
    openai:
      api-key: ${OPENAI_API_KEY}  # 환경변수로 관리
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
      image:
        options:
          model: dall-e-3
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
hybrid-search:
  tmm:
    text-score:
      max-value: 5
      min-value: 0
  weight:
    vector-score: 0.7
    text-score: 0.3
